point_lio_mapping:
  ros__parameters:
    common:
      lid_topic:  "/utlidar/cloud"
      imu_topic:  "/utlidar/imu"
      time_sync_en: false
      time_offset_lidar_to_imu: 0.0

    preprocess:
      lidar_type: 2
      scan_line: 16
      blind: 0.1
      timestamp_unit: 3
      scan_rate: 10
      point_filter_num: 1

    calibration:
      extrinsic_est_en: true
      extrinsic_T: [ 0.0, 0.0, 0.0 ]
      extrinsic_R: [ 1.0, 0.0, 0.0,
                     0.0, 1.0, 0.0,
                     0.0, 0.0, 1.0 ]

    mapping:
      acc_cov: 0.1
      gyr_cov: 0.1
      acc_bias_cov: 0.0001
      gyr_bias_cov: 0.0001
      vox_size: 0.2

    publish:
      path_en: true
      scan_publish_en: true
      dense_publish_en: true
      scan_bodyframe_pub_en: false